/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const Symbol = IDL.Text;
export const LimitOrder = IDL.Record({
  'id' : IDL.Nat,
  'orderType' : OrderType,
  'isActive' : IDL.Bool,
  'quantity' : IDL.Nat,
  'remaining' : IDL.Nat,
  'price' : IDL.Nat,
  'symbol' : Symbol,
});
export const Price = IDL.Record({ 'price' : IDL.Nat, 'symbol' : Symbol });
export const Trade = IDL.Record({
  'profitLoss' : IDL.Int,
  'orderType' : OrderType,
  'positionSize' : IDL.Nat,
  'entryPrice' : IDL.Nat,
  'exitPrice' : IDL.Nat,
  'symbol' : Symbol,
});
export const Holding = IDL.Record({ 'quantity' : IDL.Nat, 'symbol' : Symbol });
export const UserProfile = IDL.Record({
  'tradeHistory' : IDL.Vec(Trade),
  'openLimitOrders' : IDL.Vec(LimitOrder),
  'holdings' : IDL.Vec(Holding),
  'cashBalance' : IDL.Nat,
});
export const PortfolioValuation = IDL.Record({
  'openPositionsValue' : IDL.Nat,
  'totalEquity' : IDL.Nat,
  'cashBalance' : IDL.Nat,
  'holdingsValue' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'depositFunds' : IDL.Func([IDL.Nat], [], []),
  'getActiveLimitOrders' : IDL.Func([], [IDL.Vec(LimitOrder)], ['query']),
  'getAllPrices' : IDL.Func([], [IDL.Vec(Price)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHoldings' : IDL.Func([], [IDL.Vec(Holding)], ['query']),
  'getPortfolioValuation' : IDL.Func([], [PortfolioValuation], ['query']),
  'getPrice' : IDL.Func([Symbol], [IDL.Opt(Price)], ['query']),
  'getPriceStats' : IDL.Func([Symbol], [Price], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeProfile' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeLimitOrder' : IDL.Func(
      [Symbol, OrderType, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'placeMarketOrder' : IDL.Func([Symbol, OrderType, IDL.Nat], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePrice' : IDL.Func([Price], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const Symbol = IDL.Text;
  const LimitOrder = IDL.Record({
    'id' : IDL.Nat,
    'orderType' : OrderType,
    'isActive' : IDL.Bool,
    'quantity' : IDL.Nat,
    'remaining' : IDL.Nat,
    'price' : IDL.Nat,
    'symbol' : Symbol,
  });
  const Price = IDL.Record({ 'price' : IDL.Nat, 'symbol' : Symbol });
  const Trade = IDL.Record({
    'profitLoss' : IDL.Int,
    'orderType' : OrderType,
    'positionSize' : IDL.Nat,
    'entryPrice' : IDL.Nat,
    'exitPrice' : IDL.Nat,
    'symbol' : Symbol,
  });
  const Holding = IDL.Record({ 'quantity' : IDL.Nat, 'symbol' : Symbol });
  const UserProfile = IDL.Record({
    'tradeHistory' : IDL.Vec(Trade),
    'openLimitOrders' : IDL.Vec(LimitOrder),
    'holdings' : IDL.Vec(Holding),
    'cashBalance' : IDL.Nat,
  });
  const PortfolioValuation = IDL.Record({
    'openPositionsValue' : IDL.Nat,
    'totalEquity' : IDL.Nat,
    'cashBalance' : IDL.Nat,
    'holdingsValue' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'depositFunds' : IDL.Func([IDL.Nat], [], []),
    'getActiveLimitOrders' : IDL.Func([], [IDL.Vec(LimitOrder)], ['query']),
    'getAllPrices' : IDL.Func([], [IDL.Vec(Price)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHoldings' : IDL.Func([], [IDL.Vec(Holding)], ['query']),
    'getPortfolioValuation' : IDL.Func([], [PortfolioValuation], ['query']),
    'getPrice' : IDL.Func([Symbol], [IDL.Opt(Price)], ['query']),
    'getPriceStats' : IDL.Func([Symbol], [Price], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeProfile' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeLimitOrder' : IDL.Func(
        [Symbol, OrderType, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'placeMarketOrder' : IDL.Func([Symbol, OrderType, IDL.Nat], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePrice' : IDL.Func([Price], [], []),
  });
};

export const init = ({ IDL }) => { return []; };