/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Holding { 'quantity' : bigint, 'symbol' : Symbol }
export interface LimitOrder {
  'id' : bigint,
  'orderType' : OrderType,
  'isActive' : boolean,
  'quantity' : bigint,
  'remaining' : bigint,
  'price' : bigint,
  'symbol' : Symbol,
}
export type OrderType = { 'buy' : null } |
  { 'sell' : null };
export interface PortfolioValuation {
  'openPositionsValue' : bigint,
  'totalEquity' : bigint,
  'cashBalance' : bigint,
  'holdingsValue' : bigint,
}
export interface Price { 'price' : bigint, 'symbol' : Symbol }
export type Symbol = string;
export interface Trade {
  'profitLoss' : bigint,
  'orderType' : OrderType,
  'positionSize' : bigint,
  'entryPrice' : bigint,
  'exitPrice' : bigint,
  'symbol' : Symbol,
}
export interface UserProfile {
  'tradeHistory' : Array<Trade>,
  'openLimitOrders' : Array<LimitOrder>,
  'holdings' : Array<Holding>,
  'cashBalance' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'depositFunds' : ActorMethod<[bigint], undefined>,
  'getActiveLimitOrders' : ActorMethod<[], Array<LimitOrder>>,
  'getAllPrices' : ActorMethod<[], Array<Price>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHoldings' : ActorMethod<[], Array<Holding>>,
  'getPortfolioValuation' : ActorMethod<[], PortfolioValuation>,
  'getPrice' : ActorMethod<[Symbol], [] | [Price]>,
  'getPriceStats' : ActorMethod<[Symbol], Price>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeProfile' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeLimitOrder' : ActorMethod<[Symbol, OrderType, bigint, bigint], bigint>,
  'placeMarketOrder' : ActorMethod<[Symbol, OrderType, bigint], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePrice' : ActorMethod<[Price], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];