/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    tradeHistory: Array<Trade>;
    openLimitOrders: Array<LimitOrder>;
    holdings: Array<Holding>;
    cashBalance: bigint;
}
export type Symbol = string;
export interface Holding {
    quantity: bigint;
    symbol: Symbol;
}
export interface Trade {
    profitLoss: bigint;
    orderType: OrderType;
    positionSize: bigint;
    entryPrice: bigint;
    exitPrice: bigint;
    symbol: Symbol;
}
export interface PortfolioValuation {
    openPositionsValue: bigint;
    totalEquity: bigint;
    cashBalance: bigint;
    holdingsValue: bigint;
}
export interface LimitOrder {
    id: bigint;
    orderType: OrderType;
    isActive: boolean;
    quantity: bigint;
    remaining: bigint;
    price: bigint;
    symbol: Symbol;
}
export interface Price {
    price: bigint;
    symbol: Symbol;
}
export enum OrderType {
    buy = "buy",
    sell = "sell"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    depositFunds(amount: bigint): Promise<void>;
    getActiveLimitOrders(): Promise<Array<LimitOrder>>;
    getAllPrices(): Promise<Array<Price>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getHoldings(): Promise<Array<Holding>>;
    getPortfolioValuation(): Promise<PortfolioValuation>;
    getPrice(symbol: Symbol): Promise<Price | null>;
    getPriceStats(symbol: Symbol): Promise<Price>;
    getProfile(): Promise<UserProfile | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeProfile(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    placeLimitOrder(symbol: Symbol, orderType: OrderType, price: bigint, quantity: bigint): Promise<bigint>;
    placeMarketOrder(symbol: Symbol, orderType: OrderType, quantity: bigint): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updatePrice(_price: Price): Promise<void>;
}
import type { Holding as _Holding, LimitOrder as _LimitOrder, OrderType as _OrderType, Price as _Price, Symbol as _Symbol, Trade as _Trade, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async depositFunds(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.depositFunds(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.depositFunds(arg0);
            return result;
        }
    }
    async getActiveLimitOrders(): Promise<Array<LimitOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveLimitOrders();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveLimitOrders();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPrices(): Promise<Array<Price>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPrices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPrices();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHoldings(): Promise<Array<Holding>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHoldings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHoldings();
            return result;
        }
    }
    async getPortfolioValuation(): Promise<PortfolioValuation> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioValuation();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioValuation();
            return result;
        }
    }
    async getPrice(arg0: Symbol): Promise<Price | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrice(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrice(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPriceStats(arg0: Symbol): Promise<Price> {
        if (this.processError) {
            try {
                const result = await this.actor.getPriceStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPriceStats(arg0);
            return result;
        }
    }
    async getProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeProfile(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeProfile();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async placeLimitOrder(arg0: Symbol, arg1: OrderType, arg2: bigint, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.placeLimitOrder(arg0, to_candid_OrderType_n17(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeLimitOrder(arg0, to_candid_OrderType_n17(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async placeMarketOrder(arg0: Symbol, arg1: OrderType, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.placeMarketOrder(arg0, to_candid_OrderType_n17(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeMarketOrder(arg0, to_candid_OrderType_n17(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updatePrice(arg0: Price): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePrice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePrice(arg0);
            return result;
        }
    }
}
function from_candid_LimitOrder_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LimitOrder): LimitOrder {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_OrderType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderType): OrderType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Trade_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trade): Trade {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Price]): Price | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tradeHistory: Array<_Trade>;
    openLimitOrders: Array<_LimitOrder>;
    holdings: Array<_Holding>;
    cashBalance: bigint;
}): {
    tradeHistory: Array<Trade>;
    openLimitOrders: Array<LimitOrder>;
    holdings: Array<Holding>;
    cashBalance: bigint;
} {
    return {
        tradeHistory: from_candid_vec_n11(_uploadFile, _downloadFile, value.tradeHistory),
        openLimitOrders: from_candid_vec_n3(_uploadFile, _downloadFile, value.openLimitOrders),
        holdings: value.holdings,
        cashBalance: value.cashBalance
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    profitLoss: bigint;
    orderType: _OrderType;
    positionSize: bigint;
    entryPrice: bigint;
    exitPrice: bigint;
    symbol: _Symbol;
}): {
    profitLoss: bigint;
    orderType: OrderType;
    positionSize: bigint;
    entryPrice: bigint;
    exitPrice: bigint;
    symbol: Symbol;
} {
    return {
        profitLoss: value.profitLoss,
        orderType: from_candid_OrderType_n6(_uploadFile, _downloadFile, value.orderType),
        positionSize: value.positionSize,
        entryPrice: value.entryPrice,
        exitPrice: value.exitPrice,
        symbol: value.symbol
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    orderType: _OrderType;
    isActive: boolean;
    quantity: bigint;
    remaining: bigint;
    price: bigint;
    symbol: _Symbol;
}): {
    id: bigint;
    orderType: OrderType;
    isActive: boolean;
    quantity: bigint;
    remaining: bigint;
    price: bigint;
    symbol: Symbol;
} {
    return {
        id: value.id,
        orderType: from_candid_OrderType_n6(_uploadFile, _downloadFile, value.orderType),
        isActive: value.isActive,
        quantity: value.quantity,
        remaining: value.remaining,
        price: value.price,
        symbol: value.symbol
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): OrderType {
    return "buy" in value ? OrderType.buy : "sell" in value ? OrderType.sell : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trade>): Array<Trade> {
    return value.map((x)=>from_candid_Trade_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LimitOrder>): Array<LimitOrder> {
    return value.map((x)=>from_candid_LimitOrder_n4(_uploadFile, _downloadFile, x));
}
function to_candid_LimitOrder_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LimitOrder): _LimitOrder {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_OrderType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): _OrderType {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_Trade_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Trade): _Trade {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tradeHistory: Array<Trade>;
    openLimitOrders: Array<LimitOrder>;
    holdings: Array<Holding>;
    cashBalance: bigint;
}): {
    tradeHistory: Array<_Trade>;
    openLimitOrders: Array<_LimitOrder>;
    holdings: Array<_Holding>;
    cashBalance: bigint;
} {
    return {
        tradeHistory: to_candid_vec_n21(_uploadFile, _downloadFile, value.tradeHistory),
        openLimitOrders: to_candid_vec_n24(_uploadFile, _downloadFile, value.openLimitOrders),
        holdings: value.holdings,
        cashBalance: value.cashBalance
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    profitLoss: bigint;
    orderType: OrderType;
    positionSize: bigint;
    entryPrice: bigint;
    exitPrice: bigint;
    symbol: Symbol;
}): {
    profitLoss: bigint;
    orderType: _OrderType;
    positionSize: bigint;
    entryPrice: bigint;
    exitPrice: bigint;
    symbol: _Symbol;
} {
    return {
        profitLoss: value.profitLoss,
        orderType: to_candid_OrderType_n17(_uploadFile, _downloadFile, value.orderType),
        positionSize: value.positionSize,
        entryPrice: value.entryPrice,
        exitPrice: value.exitPrice,
        symbol: value.symbol
    };
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    orderType: OrderType;
    isActive: boolean;
    quantity: bigint;
    remaining: bigint;
    price: bigint;
    symbol: Symbol;
}): {
    id: bigint;
    orderType: _OrderType;
    isActive: boolean;
    quantity: bigint;
    remaining: bigint;
    price: bigint;
    symbol: _Symbol;
} {
    return {
        id: value.id,
        orderType: to_candid_OrderType_n17(_uploadFile, _downloadFile, value.orderType),
        isActive: value.isActive,
        quantity: value.quantity,
        remaining: value.remaining,
        price: value.price,
        symbol: value.symbol
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): {
    buy: null;
} | {
    sell: null;
} {
    return value == OrderType.buy ? {
        buy: null
    } : value == OrderType.sell ? {
        sell: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Trade>): Array<_Trade> {
    return value.map((x)=>to_candid_Trade_n22(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<LimitOrder>): Array<_LimitOrder> {
    return value.map((x)=>to_candid_LimitOrder_n25(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
